# Generated by Django 2.2.13 on 2021-10-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200724_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategory',
            name='priority',
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='event_category/'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('deleted', 'Deleted'), ('completed', 'Completed')], max_length=10),
        ),
    ]
