# Generated by Django 2.2.13 on 2021-10-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211028_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_category/'),
        ),
    ]
