# Generated by Django 2.2.13 on 2021-10-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20211028_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='event_category/'),
        ),
    ]
