# Generated by Django 2.2.13 on 2021-10-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20211028_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(upload_to='event_category/'),
        ),
    ]
