# Generated by Django 2.2.13 on 2021-10-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20211028_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategory',
            name='image',
        ),
    ]
