# Generated by Django 2.2.13 on 2021-10-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_eventcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='scheduled_status',
        ),
        migrations.RemoveField(
            model_name='eventagenda',
            name='session_name',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancel', 'Cancel')], max_length=10),
        ),
    ]
