# Generated by Django 2.2.13 on 2021-10-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20211028_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmember',
            name='attend_status',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='status',
        ),
        migrations.AddField(
            model_name='eventmember',
            name='college',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
