# Generated by Django 2.2.13 on 2021-10-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20211028_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventUserWishList',
        ),
    ]
