# Generated by Django 2.2.13 on 2021-10-28 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_delete_eventuserwishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoin',
            name='gain_coin',
        ),
        migrations.RemoveField(
            model_name='usercoin',
            name='gain_type',
        ),
        migrations.AddField(
            model_name='usercoin',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AlterField(
            model_name='usercoin',
            name='status',
            field=models.CharField(choices=[('winner', 'Winner'), ('1runnerup', '1st Runner Up'), ('2runnerup', '2nd Runner Up')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usercoin',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
